### ISSUE TITLE
Extend Google Analytics to report time spent on pages

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/vets-api#11814]
### Issue Description

VA currently uses Data Analytics to gather data and insights about how the Veteran Facing sites are used, and Domo presents a Dashboard to make that data more accessible across teams. (Big Query is also used in the mix to transform the data and make it more insightful before it is imported into Domo.)

### Preliminary Questions/Assumptions

- Is Google Analytics the best tool for this use case?
- Do we want this data exposed in Domo?
- Would 526 team find it helpful to review this data in Domo?
- Do other pages within VFS offer this granularity of functionality?
- Domo currently has a single page for many of VA.gov's forms, and presumably those other forms don't have tracking at this level of granularity. How would this change affect Domo's Forms dashboard if the 526 Form is the only one intentionally capturing this data?

### Tasks

- [ ] Check in with Michelle Dooley's Analytics team on the best approach for this work.
- [ ] Extend Data Analytics current site monitoring to collect data on how long a Vet spends on each page of the 526 form
- [ ] Transform and import this data to Domo
- [ ] Create a card in Domo to surface this data within the filter for 526 forms

### Acceptance Criteria

- [ ] 526 Form team has the data they need to inform their design.

**Comment by navaeddie** [comment]
Regarding our goal to learn more about [time to completion](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/analytics/want-to-know.md#now), Michelle Dooley in analytics suggested Google Analytics probably can't provide the level of detail we are looking for on this. So perhaps we should close this card and I can focus on finding the underlying data in one of the VA's databases.
