### ISSUE TITLE
Pre-Launch Checklist

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/vets-api#179]
The purpose of this issue is to identify candidates for further scrutiny prior to launching to production. Please add additional checklists and open more granular issues as you encounter them.
- [x] Ensure we're using Time.current.utc across the vets-api project
- [ ] Ensure that the Rails App has TimeZone specified independent of the server on which it is running. (Similarly Devops should double check NTP and system times are UTC).
- [ ] Audit all API endpoints and ensure that they are consistent with JSON API specification v1.0
- [ ] Audit all API endpoints and ensure that they are consistent with handling common things like handling arrays passed as query params, pagination, filtering, sorting, etc.

**Comment by jcmeloni** [comment]
@saneshark @ayaleloehr What are we still doing here, given we're past launch :) (we are trying to clean up issues)

**Comment by ayaleloehr** [comment]
Leaving this one to @saneshark .

**Comment by saneshark** [comment]
Closing this for now. I am nearly certain our endpoints are not consistent, but our controllers are also v0, perhaps when we approach a v1 and are out of beta, this will be more important.
