### ISSUE TITLE
Enable V2::ContactInformation::Service in all tests

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/vets-api#18408]
## User Story
As the engineers working on the EVSS PCIU migration objective,
It is is important that the v2::ContactInformation is updated to v3::ProfileInformation
So that the [EVSS PCIU migration](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73776) work can be completed

## Issue Description
V2::ContactInformation::Service needs to be enabled for all rspec tests. To move forward with V2::ContactInformation::Service testing, the service was disabled in other places not using V2::ContactInformation

Specs to update:
- [ ] modules/mobile/spec
- [ ] spec/lib/lighthouse/benefits_documents
- [ ] spec/lib/va_profile/person
- [ ] spec/rakelib
- [ ] spec/requests/swagger_spec.rb
- [ ] spec/requests/v0/profile
- [ ] spec/sidekiq/copay_notifications/mcp_notification_email_job_spec.rb

## Tasks
- [ ] Enable V2::ContactInformation::Service
- [ ] Update VCRs, if necessary

## Success Metrics
- [ ] Tests passing with V2::ContactInformation::Service

## Acceptance Criteria
- [ ] V2::ContactInformation::Service has been enabled for all tests
---

## Validation
_Assignee to add steps to this section. List the actions that need to be taken to confirm this issue is complete. Include any necessary links or context. State the expected outcome._
