### ISSUE TITLE
Generate swagger docs for the Health Quest Service

### ISSUE THREAD

**Issue by massrb** [department-of-veterans-affairs/vets-api#5055]
## Tasks
- [x] Research swagger generation and how other modules/engines swaggers work
- [x] Generate swagger for the health quest service, make sure it is accessible and can be updated

## Acceptance Criteria
- [ ] The swagger is accessible from vets-api 
- [ ] check the code into the main branch
- [ ] Have M. Dewey review it.
